### ISSUE TITLE
Scrolling is broken by supporter badges

### ISSUE THREAD

**Issue by dmryabov** [sc2tvru/chat-sc2tv#8]
Похоже, что из-за того, что у добавляемого изображения в теге `<img>` не заданы размеры (https://github.com/sc2tvru/chat-sc2tv/blob/master/js/chat.js#L796) их вычисление происходит в после срабатывания автопрокрутки, из-за чего последние строчка-две не доскролливаются. Баг в Chrome/Opera последних на windows. Задание обоих размеров в css не помогают. Как решение - либо добавить `width="12" height="11"` к `<img>`, либо сделать их в css

``` css
.nick.top-supporter:before {
  content: '';
  display: inline-block;
  width: 12px;
  height: 11px;
  margin-right: 2px;
  background-image: url('donate_01.png');
  background-size: contain;
}
```

добавляя соответствующий класс к нику, как добавляются цвета перед этим.
